version: '3'

services:
  ocpp:
    image: 'ocpp:latest'
    build:
      dockerfile: Dockerfile
    container_name: csms-0.0.1-SNAPSHOT
    depends_on:
      - ocpp-db
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  ocpp-db:
    image: 'postgres:latest'
    container_name: ocpp-db
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
