version: '3'

services:
  ocpp:
    image: 'ocpp:latest'
    build:
      context: csms
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL = jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=username
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    container_name: db
    build: ./dependencies/postgres
    image: db
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    expose:
      - "5432"
    ports:
      - "5432:5432"
